import { Divider } from "@/components/Divider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Footer } from "./_components/footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <header className="my-6 flex items-center flex-col">
          <Link
            href="/"
            className="text-center font-bold text-4xl hover:scale-105 duration-300"
          >
            Core Web Vitals Demo
          </Link>
          <Divider />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
